---
title: 'Estimate Dark Rate of Crime'
geometry: margin=1cm
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

### Set Basic Values
```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, tidy=TRUE, tidy.opts = list(width.cutoff=80))
```

Clear Environment
```{r}
rm(list = ls())
```

Load Packages
```{r echo=T, results='hide'}
library(psych)
library(kableExtra)
library(drcr)
```

Set Seed for Reproducibility
```{r}
set.seed(123)
```

Set Basic Values
```{r}
n <- 100000
```

### Create Simulation Data
```{r}
parm_sim0 <- set_parms()
parm_sim <- parm_sim0[3:length(parm_sim0)]
data0 <- sim_data(n, parm_sim0)
data <- data0[,1:4]

```

### Estimate Parameters
```{r}
params0 <- set_inits()
#result <- wrap_optim(data, params0, LF)
result <- wrap_optim(data, params0, LF, grad=LF_gradient)
```

### Show Results
```{r}
result_table <- get_results(data, result)
sim.values <- c(parm_sim, E_hat=mean(data0[,'E']), C_hat=mean(data0[,'C']))
result_table <- cbind(sim.values, result_table)
kable(result_table)
```
### Estimate Dark Rate: 
DRC = 1 - R/C
```{r}
DRC <- get_dark_rate(mean(data[,'R']), result_table['C_hat',]$estimates)
cat("DRC: ", DRC, "\n")
```

### Show Summary Statistics
```{r}
kable(describe(data))
```
### Show Correlation Table
```{r}
kable(cor(data))
```
